### ISSUE TITLE
Support for config parameters

### ISSUE THREAD

**Issue by westshawn** [grundic/teamcity-web-parameters#5]
I would like to parameterize the url for web parameters like this 
```
http://webservice/%PROJECT_ID% 
```

Is this possible?

TeamCity doesn't seem to recognize parameter references in the url and the url doesn't seem to resolve the parameters in the url.

**Comment by grundic** [comment]
Hello, @westshawn
Yes, it should be possible. Right now I'm pn vacation. But after that I
will implement it.
Thank you for your request.

On Monday, August 31, 2015, westshawn <notifications@github.com> wrote:

> I would like to parameterize the url for web parameters like this {code}
> http://webservice/%PROJECT_ID% {code}
>
> Is this possible?
>
> TeamCity doesn't seem to recognize parameter references in the url and the
> url doesn't seem to resolve the parameters in the url.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grundic/teamcity-web-parameters/issues/5>.
>


-- 
___________________________________
Best Regards, Grigory

**Comment by grundic** [comment]
Unfortunately it turned out to be impossible to implement with current TeamCity API.
I talked on the [forum](https://teamcity-support.jetbrains.com/hc/en-us/community/posts/206688055-How-to-expand-parameters-) and played with code, but I think that I need support and refactoring from TeamCity side to implement this feature. I'm not pushing them actively, so I don't expect this issue to be resolved soon :(

**Comment by grundic** [comment]
I fixed that in [v.1.5.0](https://github.com/grundic/teamcity-web-parameters/releases/tag/v1.5.0).
